credentials:
  usernames:
    leah:
      email: leah@gmail.com
      name: Leah
      password: leah  # Will be hashed automatically
      failed_login_attempts: 0  # Will be managed automatically
      logged_in: False  # Will be managed automatically
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
pre-authorized:
  emails:
    - melsby@gmail.com
